// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: login.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogIn_LogInUser_FullMethodName = "/LogIn/LogInUser"
)

// LogInClient is the client API for LogIn service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogInClient interface {
	LogInUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type logInClient struct {
	cc grpc.ClientConnInterface
}

func NewLogInClient(cc grpc.ClientConnInterface) LogInClient {
	return &logInClient{cc}
}

func (c *logInClient) LogInUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, LogIn_LogInUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogInServer is the server API for LogIn service.
// All implementations must embed UnimplementedLogInServer
// for forward compatibility.
type LogInServer interface {
	LogInUser(context.Context, *UserRequest) (*LoginResponse, error)
	mustEmbedUnimplementedLogInServer()
}

// UnimplementedLogInServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogInServer struct{}

func (UnimplementedLogInServer) LogInUser(context.Context, *UserRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogInUser not implemented")
}
func (UnimplementedLogInServer) mustEmbedUnimplementedLogInServer() {}
func (UnimplementedLogInServer) testEmbeddedByValue()               {}

// UnsafeLogInServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogInServer will
// result in compilation errors.
type UnsafeLogInServer interface {
	mustEmbedUnimplementedLogInServer()
}

func RegisterLogInServer(s grpc.ServiceRegistrar, srv LogInServer) {
	// If the following call pancis, it indicates UnimplementedLogInServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogIn_ServiceDesc, srv)
}

func _LogIn_LogInUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogInServer).LogInUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogIn_LogInUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogInServer).LogInUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogIn_ServiceDesc is the grpc.ServiceDesc for LogIn service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogIn_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LogIn",
	HandlerType: (*LogInServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogInUser",
			Handler:    _LogIn_LogInUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login.proto",
}
